import asyncio
import json
import logging
import re
from pathlib import Path

import anthropic

from models.intake import IntakeData
from models.program import GeneratedProgram, ProgramExercise

logger = logging.getLogger(__name__)

_client = anthropic.Anthropic()

_EXERCISE_LIBRARY_PATH = Path(__file__).parent.parent.parent / "data" / "exercise_library.json"
with _EXERCISE_LIBRARY_PATH.open() as f:
    _EXERCISE_LIBRARY: dict = json.load(f)

SYSTEM_PROMPT = """You are a physiotherapist-grade AI assistant helping design safe, personalised lower back pain rehabilitation programs.

Given a patient's intake information you will select 5-7 exercises from the provided library and configure sets and reps appropriate for their pain level and duration.

Guidelines:
- NPRS >= 7: prioritise gentle mobility (cat_cow, knee_to_chest, child_pose), low reps (6-8), no loading exercises
- NPRS 4-6: balanced mix of CV-scored strengthening and mobility, 8-10 reps
- NPRS <= 3: can include all CV exercises, 10-12 reps
- Always include at least 2 CV-scored exercises so the camera-based feedback system has targets
- Always include at least 1 mobility/self-paced exercise
- Provide a one-sentence rationale for each exercise inclusion

Return ONLY valid JSON in this exact structure (no markdown, no explanation):
{
  "week_number": 1,
  "exercises": [
    {
      "exercise_id": "pelvic_tilt",
      "name": "Pelvic Tilt",
      "type": "cv",
      "sets": 2,
      "reps": 10,
      "rest_seconds": 30,
      "rationale": "Activates deep lumbar stabilisers without loading the spine"
    }
  ],
  "program_notes": "Start slowly and rest on any days with pain > 7/10",
  "generated_by": "claude"
}"""


def _build_user_prompt(intake: IntakeData) -> str:
    library_summary = json.dumps(
        [
            {
                "id": e["id"],
                "name": e["name"],
                "type": e["type"],
                "contraindications": e.get("contraindications", []),
            }
            for e in _EXERCISE_LIBRARY["exercises"]
        ],
        indent=2,
    )
    return f"""Patient intake:
- Pain location: {intake.pain_location}
- Current pain (NPRS 0-10): {intake.nprs_baseline}
- Duration: {intake.duration_weeks} weeks
- Prior physiotherapy or GP care: {intake.prior_care}
- Occupation: {intake.occupation or 'not specified'}

Available exercises:
{library_summary}

Please generate a personalised Week 1 program."""


def _extract_json(text: str) -> str:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        return match.group(0)
    return text


def _build_fallback_program(intake: IntakeData) -> GeneratedProgram:
    if intake.nprs_baseline >= 7:
        exercise_ids = ["cat_cow", "knee_to_chest", "child_pose", "pelvic_tilt"]
        reps = 6
    elif intake.nprs_baseline >= 4:
        exercise_ids = ["pelvic_tilt", "cat_cow", "glute_bridge", "knee_to_chest", "child_pose"]
        reps = 8
    else:
        exercise_ids = ["pelvic_tilt", "glute_bridge", "bird_dog", "dead_bug", "cat_cow", "child_pose"]
        reps = 10

    ex_map = {e["id"]: e for e in _EXERCISE_LIBRARY["exercises"]}
    exercises = [
        ProgramExercise(
            exercise_id=eid,
            name=ex_map[eid]["name"],
            type=ex_map[eid]["type"],
            sets=ex_map[eid].get("default_sets", 2),
            reps=reps,
            hold_seconds=ex_map[eid].get("hold_seconds"),
            rest_seconds=ex_map[eid].get("rest_seconds", 30),
            rationale=None,
        )
        for eid in exercise_ids
        if eid in ex_map
    ]
    return GeneratedProgram(
        week_number=1,
        exercises=exercises,
        program_notes="Standard program. Complete on 3 non-consecutive days per week.",
        generated_by="fallback",
    )


async def generate_program(intake: IntakeData) -> GeneratedProgram:
    try:
        response = await asyncio.to_thread(
            _client.messages.create,
            model="claude-sonnet-4-6",
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _build_user_prompt(intake)}],
        )
        text = response.content[0].text
        raw_json = _extract_json(text)
        program = GeneratedProgram.model_validate_json(raw_json)
        logger.info("program generated by claude exercises=%d", len(program.exercises))
        return program
    except Exception as exc:
        logger.warning("claude program generation failed, using fallback: %s", exc)
        return _build_fallback_program(intake)